### ISSUE TITLE
demo: arxiv summarizer

### ISSUE THREAD

**Issue by edublancas** [ploomber/doc#87]
build a chat application that can summarize the latest papers for a given area

- to begin with, let's focus on computer science papers
- arxiv has some paper taxonomy,perhaps we can use it to select sub areas of CS (e.g., AI/ML)
- once the user selects an area  we can display the abstracts for the most recent papers
- we can produce a 1-2 sentence summary by passing the abstract through OpenAI
- then users can ask other questions like: please tell me more about paper X, or give me alink to download paper Y

some code to get started: [arxiv.ipynb.zip](https://github.com/ploomber/doc/files/14070420/arxiv.ipynb.zip)

**Comment by edublancas** [comment]
you can use this as an example: https://github.com/ploomber/doc/blob/main/examples/panel/rag-news/app.py

but let's use solara for this one.

and here's a tutorial that I wrote on RAGs: [rag.ipynb.zip](https://github.com/ploomber/doc/files/14106668/rag.ipynb.zip)

we can use function calling to do this: https://platform.openai.com/docs/guides/function-calling

**Comment by edublancas** [comment]
btw, let's get this one done without any RAG libraries (just the openAI API), they often add a lot of dependencies and make the deployment process clunky.

**Comment by edublancas** [comment]
some feedback:


- allow typing enter to send the message
- move chat box to the bottom
- instad of "AI system" let's but "Built by Ploomber" and link to our website
- order of messages is inverted, most recent ones should appear at the bottom
- change the title from "Scientific Artcicle Chat" to "Arxiv Chat"
- asked: is there anything new on LLMs?


```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/reacton/ipyvue.py", line 23, in handler
    callback_ref.current(*args)
  File "/usr/local/lib/python3.11/site-packages/solara/components/button.py", line 84, in <lambda>
    ipyvue.use_event(btn, click_event, lambda *_ignore: on_click and on_click())
                                                                     ^^^^^^^^^^
  File "/srv/chat.py", line 115, in ask_chatgpt
    for new_message in oc.article_chat(input):
  File "/srv/ai.py", line 182, in article_chat
    content = self.call_tool(function_call)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/ai.py", line 143, in call_tool
    content = getattr(self, func_name)(args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/ai.py", line 95, in get_authors
    article = self.get_article_by_title(arguments["title"])
                                        ~~~~~~~~~^^^^^^^^^
KeyError: 'title'

```


- asked: tell me about the most recent cryotpgraphy papers (tip: use tiktoken to count the tokens to prevent this), also happened when doing "tell me about the most recent ML papers"

got:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/reacton/ipyvue.py", line 23, in handler
    callback_ref.current(*args)
  File "/usr/local/lib/python3.11/site-packages/solara/components/button.py", line 84, in <lambda>
    ipyvue.use_event(btn, click_event, lambda *_ignore: on_click and on_click())
                                                                     ^^^^^^^^^^
  File "/srv/chat.py", line 113, in ask_chatgpt
    load_articles_from_topic_query(input)
  File "/srv/chat.py", line 103, in load_articles_from_topic_query
    for new_message in oc.article_chat("Summarize each article in a sentence"):
  File "/srv/ai.py", line 157, in article_chat
    response = self.client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_utils/_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 659, in create
    return self._post(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1200, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 889, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 980, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 4097 tokens. However, your messages resulted in 4557 tokens (4411 in the messages, 146 in the functions). Please reduce the length of the messages or functions.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

```
